version: '3'

services:
  sshcli:
    image: zworkroman/sshcli
    restart: unless-stopped
    environment:
      - SSHCLI_SSH_ID_ACCESS=${SSHCLI_SSH_ID_ACCESS:-}
      - SSHCLI_SSH_CONFIG=${SSHCLI_SSH_CONFIG:-}
    command: [ "ssh", "-NL", "0.0.0.0:80:${HOST:-localhost}:${HOST_PORT:-80}", "${PROXY_HOST}" ]
